### ISSUE TITLE
Fix E776 on lhelpgrep when g:qf_auto_open_loclist=1

### ISSUE THREAD

**Issue by perelo** [romainl/vim-qf#110]
Not properly a vim-qf's issue, but when executing `:lhelpgrep {pat}` with the current `autocmd`s when `g:qf_auto_open_loclist=1` vim will issue

    Error detected while processing QuickFixCmdPost Autocommands for "l*"..function qf#OpenLoclist:
    line   12:
    E776: No location list

Even though there's some results and a following `lwindow` opens correctly the location list. See [this question](https://vi.stackexchange.com/questions/8327/how-to-automatically-open-the-location-list-window-after-using-the-lhelpgrep-co).

The minimal proposed correction is not pretty but works for me. There are other ways.

```diff
--- a/plugin/qf.vim
+++ b/plugin/qf.vim
@@ -64,9 +64,12 @@ augroup qf
    autocmd!

    " automatically open the location/quickfix window after :make, :grep,
-    " :lvimgrep and friends if there are valid locations/errors
+    " :lvimgrep and friends if there are valid locations/errors,
+    " delay for :lhelpgrep since the help window may not be opened yet when
+    " QuickFixCmdPost triggers
    autocmd QuickFixCmdPost [^l]* nested call qf#OpenQuickfix()
-    autocmd QuickFixCmdPost    l* nested call qf#OpenLoclist()
+    autocmd QuickFixCmdPost l[^h]* nested call qf#OpenLoclist()
+    autocmd QuickFixCmdPost lh* nested call timer_start(10, { -> execute('call qf#OpenLoclist()') })
    autocmd VimEnter            * nested call qf#OpenQuickfix()

    " automatically close corresponding loclist when quitting a window
```

Surely, it follows the default behaviour of vim which also throws `E776`, but maybe vim-qf could "solve" that.

**Comment by romainl** [comment]
Thank you for bringing this up.

FWIW, there is a related issue with `:helpgrep`, where vim-qf opens the qf window at the bottom of the screen before Vim splits the window to show the help, meaning that the alternate buffer is the quickfix buffer, the previous window is the quickfix window, and the quickfix window is not at its desired location at the bottom of the screen. Bad.

I agree that the proposed solution is not pretty but it seems to be OK for the time being. The right solution is probably along the lines of:

* adding `[^h]` to all autocommand patterns so that both `:helpgrep` and `:lhelpgrep` are left out of the "default" behaviour,
* and adding autocommands on help window creation that figure out if either `:helpgrep` or `:lhelpgrep` has been used and call the appropriate functions.

**Comment by perelo** [comment]
> Thank you for bringing this up.

Thank you for taking it into account.

> FWIW, there is a related issue with :helpgrep

You're right, I didn't notice. What I see is the main trouble is to detect whether `:l?helpgrep` returned some results or not. If we could catch this info in `QuickFixCmdPost`, we could do something.

For example, with `:helpgrep` we can compare the number of quickfix lists between `QuickFixCmdPre` and `QuickFixCmdPost` with `getqflist({'nr':'$'})`. But it does not work for the location list.


>   * and adding autocommands on help window creation that figure out if either :helpgrep or :lhelpgrep has been used and call the appropriate functions.

Yes but it doesn't seem easy to do. The command may not be in the `:` history, when executed in mappings for example.

**Comment by romainl** [comment]
From what I understand, Vim seems to do the equivalent of `:vimgrep foo <list of all tags files>` and then `:cfirst`. I am just not sure what to do with that.

> For example, with `:helpgrep` we can compare the number of quickfix lists between `QuickFixCmdPre` and `QuickFixCmdPost` with `getqflist({'nr':'$'})`. But it does not work for the location list.

The quickfix list may have the same number of entries before and after anyway.

I intuitively don't like that timer-based hack because of the magic `10` and all, but it has the distinct advantage of working.

**Comment by romainl** [comment]
I'll close this for now as most of it is done. If anyone finds a solution for `:lhelpgrep`, feel free to open a PR.
