### ISSUE TITLE
qf_qf_toggle not working in windows under neovim

### ISSUE THREAD

**Issue by anoop1005** [romainl/vim-qf#123]
Tried the below mapping. But quick fix window is not toggling after doing a vimgrep 

     map <leader>q <Plug>(qf_qf_toggle)

In the `function! qf#toggle#ToggleQfWindow(stay) abort`, `qf#IsQfWindowOpen()` is not returning `true` instead the below statement is getting executed:

    else
        execute get(g:, 'qf_auto_resize', 1) ? min([ max_height, len(getqflist()) ]) . 'cwindow' : max_height . 'cwindow'

**Comment by romainl** [comment]
Hi, I took the liberty to reformat your post to make it more legible.

Anyway, this plugin is strictly a Vim plugin that comes with no guarantee whatsoever of working in other editors. Since I don't use Neovim I don't plan to provide support for that editor.

If you also encounter that problem in Vim, please provide the following information:
- Vim version: the full output of `:version`,
- vim-qf version: the last stable release is 0.2.0

**Comment by anoop1005** [comment]
This issue can be closed. I installed the plugin to vim on windows & the feature is working.

Again tried with neovim, the feature is working fine with neovim as well.
