### ISSUE TITLE
Reformat location/quickfix list

### ISSUE THREAD

**Issue by blueyed** [romainl/vim-qf#31]
@tweekmonster provided a nice gem at https://github.com/neomake/neomake/pull/325#issuecomment-268421805, which reformats a location list to condense/remove the filename etc.

What do you think about including something like this in vim-qf?!

For reference (just renamed the function, and removed the leading space with the `printf`):

```vim
function! MyQuickfixReformat() abort
  echomsg 'reformat'
  let ul = &l:undolevels
  setlocal modifiable nonumber undolevels=-1
  silent % delete _

  let lnum_width = 0
  let col_width = 0

  let loclist = getloclist(0)
  for item in loclist
    let lnum_width = max([len(item.lnum), lnum_width])
    let col_width = max([len(item.col), col_width])
  endfor

  let lines = []
  for item in loclist
    let type = toupper(item.type)
    if empty(type)
      let type = '?'
    endif
    call add(lines, printf('%*s:%*s [%s] %s', lnum_width, item.lnum, col_width, item.col, type, item.text))
  endfor

  call setline(1, lines)
  let &l:undolevels = ul
  setlocal nomodifiable nomodified
endfunction
```

@tweekmonster
Any update on the snippet you provided there?
How do you call it?  On `FileType qf`?
I use it like this, where `b:isLoc` is provided by vim-qf:
```vim
augroup vimrc_reformat_loclist
  au FileType qf if b:isLoc | call MyQuickfixReformat() | endif
augroup END
```

I think it would make sense to have it with quickfix windows, too.
There it should display the filenames always (but abbreviated).
As for the location lists, it is possible to have files for other buffers therein, too.  Therefore it should only remove the bufname when it's for the location list's buffer probably.

**Comment by romainl** [comment]
Sorry but the filename is an important information that should *always* be there.

I could accept a solution that truncates filenames so we get a nice column layout, though.

**Comment by blueyed** [comment]
> Sorry but the filename is an important information that should always be there.

Even for a location list that is for a single buffer only?
This might become an option then - I'd rather see it in the window title (`w:quickfix_title`) instead.
For shortening however, `pathshorten(fnamemodify(bufname(entry.bufnr), ':~:.'))` could be used.

**Comment by romainl** [comment]
> Even for a location list that is for a single buffer only?

The location list is tied to a single window, not buffer, and there's nothing in its design that implies it's supposed to display locations from a single buffer/file (think `:lgrep` for example).

No, I won't add this feature to vim-qf.

**Comment by tweekmonster** [comment]
> How do you call it? On FileType qf?

Used the `FileType` autocmd since the quickfix-specific autocmds only work with certain commands.  But, it stops working if the list is updated while the quickfix buffer is already open.  I haven't gotten too far in development since I posted the snippet.

I think it'll be better as a PR for Neomake since its autocmd's are a clearer signal for updating the buffer.  Also, @romainl makes a good point about the location list not always being exclusive to the current buffer.  In Neomake, that assumption can be made.

> The location list is tied to a single window, not buffer, and there's nothing in its design that implies it's supposed to display locations from a single buffer/file (think :lgrep for example).

Not arguing for or against doing anything since this can easily be a separate plugin without interfering with this one.  But, you have to admit that the filename is the most useless piece of information in the location list if it only pertains to a single buffer.  Especially if it's taking up more than half of the window and you expect the list to only be for a buffer you're looking at currently.

In the case you cited, `QuickFixCmdPost` could be used to signal when the qf buffer shouldn't be altered.  Without using the autocmd, the list could be checked and if it only mentions a single buffer, reformat the qf buffer regardless of the command.

I don't think a stylistic overhaul in the qf buffer fits with what this plugin does.  But, it could use syntax to conceal the current window's buffer path with `%` just to shorten it.
